#!/usr/bin/env pwsh
# scripts/notes/promote.ps1
# ─────────────────────────────────────────────────────────────────────────────
# Promote notes from merged commits to squad/state:decisions.md.
# Called by ralph-watch after a PR merges into the target branch.
#
# Algorithm:
# 1. Traverse commits reachable from $Branch that have notes in any squad/* namespace
# 2. For each note where promote_to_permanent == true (and not already promoted)
# 3. Append a formatted entry to decisions.md on the squad/state branch
# 4. Push state branch
#
# Usage:
#   ./scripts/notes/promote.ps1 -Branch main
#   ./scripts/notes/promote.ps1 -Branch main -DryRun
# ─────────────────────────────────────────────────────────────────────────────

[CmdletBinding()]
param(
    [string]$Branch    = "main",
    [string]$RepoPath  = ".",
    [string]$Remote    = "origin",
    [switch]$DryRun,
    [switch]$Quiet
)

$ErrorActionPreference = "Stop"

function Log ([string]$msg, [string]$color = "White") {
    if (-not $Quiet) { Write-Host "[notes/promote]$(if($DryRun){' [DRY-RUN]'}) $msg" -ForegroundColor $color }
}

$repo = Resolve-Path $RepoPath
$label = if ($DryRun) { "[DRY-RUN] " } else { "" }

# ── Fetch fresh notes ──────────────────────────────────────────────────────
Log "Fetching notes..."
git -C $repo fetch $Remote "refs/notes/*:refs/notes/*" 2>&1 | Out-Null
git -C $repo fetch $Remote "squad/state:refs/remotes/$Remote/squad/state" 2>&1 | Out-Null

# ── Find all squad/* note namespaces ─────────────────────────────────────────
$namespaces = git -C $repo for-each-ref "refs/notes/squad/" --format="%(refname:short)" 2>&1 |
              Where-Object { $_ -ne "" }

if (-not $namespaces) {
    Log "No squad notes found. Nothing to promote." DarkGray
    return
}

# ── Traverse reachable commits and find promotable notes ────────────────────
Log "Scanning commits reachable from $Remote/$Branch..."
$commits = git -C $repo log "$Remote/$Branch" --format="%H" 2>&1 |
           Where-Object { $_ -match "^[0-9a-f]{40}" }

$promotable = [System.Collections.Generic.List[object]]::new()

foreach ($sha in $commits) {
    foreach ($ns in $namespaces) {
        $note = git -C $repo notes --ref=$ns show $sha 2>&1
        if ($LASTEXITCODE -ne 0 -or -not $note) { continue }

        # Try to parse JSON
        try {
            $noteLines = if ($note -is [array]) { $note -join "`n" } else { $note }
            # Handle appended notes (may be multiple JSON objects or newline-separated)
            $entries = $noteLines -split '(?<=\})\s*(?=\{)' |
                       Where-Object { $_.Trim() } |
                       ForEach-Object {
                           try { $_ | ConvertFrom-Json -ErrorAction Stop } catch { $null }
                       } |
                       Where-Object { $_ -ne $null }

            foreach ($entry in $entries) {
                if ($entry.promote_to_permanent -eq $true) {
                    $promotable.Add(@{
                        Sha       = $sha
                        Namespace = $ns
                        Entry     = $entry
                    })
                }
            }
        } catch {
            Log "  Warning: could not parse note on $($sha.Substring(0,8)) in $ns" DarkYellow
        }
    }
}

Log "Found $($promotable.Count) promotable note(s)" Green

if ($promotable.Count -eq 0) { return }

# ── Read current decisions.md from state branch ──────────────────────────────
$decisionsContent = git -C $repo show "$Remote/squad/state:decisions.md" 2>&1
if ($LASTEXITCODE -ne 0) {
    $decisionsContent = "# Squad Decisions`n`n_Auto-generated by Ralph promotion loop._`n`n"
}

$existing = if ($decisionsContent -is [array]) { $decisionsContent -join "`n" } else { $decisionsContent }
$newEntries = [System.Collections.Generic.List[string]]::new()

foreach ($item in $promotable) {
    $shortSha  = $item.Sha.Substring(0,8)
    $entry     = $item.Entry

    # Skip if already promoted (check if SHA already in decisions.md)
    if ($existing -match $shortSha) {
        Log "  Already promoted: $shortSha ($($entry.decision ?? $entry.type))" DarkGray
        continue
    }

    $date    = if ($entry.timestamp) { $entry.timestamp.Substring(0,10) } else { (Get-Date -Format "yyyy-MM-dd") }
    $agent   = $entry.agent ?? "Unknown"
    $type    = $entry.type  ?? "decision"

    $mdEntry = @"

## [$shortSha] $date — $agent ($type)
**Namespace**: $($item.Namespace)
$(if ($entry.decision)  { "**Decision**: $($entry.decision)`n" })
$(if ($entry.reasoning) { "**Reasoning**: $($entry.reasoning)`n" })
$(if ($entry.findings)  { "**Findings**: $(($entry.findings | ConvertTo-Json -Compress))`n" })
$(if ($entry.conclusion){ "**Conclusion**: $($entry.conclusion)`n" })
"@

    $newEntries.Add($mdEntry)
    Log "  ${label}Promoting: $shortSha ($agent — $($entry.decision ?? $entry.type))" Green
}

if ($newEntries.Count -eq 0) {
    Log "All promotable notes already in decisions.md." DarkGray
    return
}

# ── Write to a temp file and commit to state branch ─────────────────────────
if (-not $DryRun) {
    $tmpDir   = Join-Path $env:TEMP "squad-state-promote-$(Get-Random)"
    New-Item -ItemType Directory -Path $tmpDir -Force | Out-Null

    try {
        # Checkout state branch into tmpDir
        git -C $repo worktree add -q $tmpDir "squad/state" 2>&1 | Out-Null

        $decisionsFile = Join-Path $tmpDir "decisions.md"
        $currentContent = if (Test-Path $decisionsFile) { Get-Content $decisionsFile -Raw } else { $existing }
        $newContent = $currentContent + ($newEntries -join "`n")

        Set-Content -Path $decisionsFile -Value $newContent -Encoding UTF8
        git -C $tmpDir add "decisions.md"
        git -C $tmpDir commit -q -m "chore(state): promote $($newEntries.Count) note(s) to decisions.md"
        git -C $tmpDir push $Remote "squad/state" 2>&1 | Out-Null

        Log "State branch updated with $($newEntries.Count) new decision(s)." Green
    } finally {
        git -C $repo worktree remove $tmpDir --force 2>&1 | Out-Null
        Remove-Item $tmpDir -Recurse -Force -ErrorAction SilentlyContinue
    }
} else {
    Log "DRY RUN — would append $($newEntries.Count) entries to decisions.md"
    $newEntries | ForEach-Object { Write-Host $_ -ForegroundColor DarkGray }
}
